config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root '/', controller: 'user', action: 'login'

  match 'login', to: 'user#login', via:[:get]

  resources :user do
    collection do
      match :login,via: [:get,:post]
      get :list
    end
  end
end

app/models/feedback.rb
# Model Feedback
class Feedback < ActiveRecord::Base
  self.table_name = 'feedbacks'

  belongs_to :user
  validates_presence_of :message
end

app/models/payment.rb
# Payment Model
class Payment < ActiveRecord::Base
  self.table_name = 'payments'

  belongs_to :user
end

app/models/practice.rb
# Model Practice
class Practice < ActiveRecord::Base
  self.table_name = 'practices'
  belongs_to :user
end

app/models/user.rb
# Model User
class User < ActiveRecord::Base
  self.table_name = 'users'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout :false,only: [:login]

  def index

  end

  def login
    return unless request.post?
    if params[:phone].blank? || params[:password].blank?
      flash[:alert] = '请输入用户名或密码'
      return
    end

    if params[:phone] == "admin" && params[:password] = "admin"
      flash[:notice] = '登陆成功'
      redirect_to :action => index
    else
      flash[:alert] = '用户名或密码输入错误'
    end
  end

  def list
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #【引数】 提示框样式选择
  #【返回】
  #【注意】
  #【著作】lx by 2018-6-14
  def switch_key(key)
    case key.to_s
    when 'alert'
      'warning'
    when 'notice'
      'success'
    else
      key
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/common/_before.html.erb
		<!-- start: TOPBAR -->
		<header class="topbar navbar navbar-fixed-top inner ">
			<div class="color-line"></div>
			<div id="logo" class="light-version">
              <%= image_tag '', :height => '52' %>
				<!--<span>ビジネスナビ</span>-->
			</div>
      <div class="container">
        <div class="navbar-header">

        </div>
			<!-- start: TOPBAR CONTAINER -->
				<div class="topbar-tools">
					<!-- start: TOP NAVIGATION MENU -->
					<ul class="nav navbar-right">
						<!-- start: USER DROPDOWN -->
						<li class="dropdown current-user">
							<a data-toggle="dropdown" class="dropdown-toggle" data-stopPropagation="true" href="#">
                <%= image_tag 'anonymous.jpg' ,:class => 'img-circle',:width => '30',height: '30',:style=>'display:inline-block; line-height:30px; vertical-align: middle; overflow:hidden;'%>
                <span class="username hidden-xs">管理者</span>
								<i class="fa fa-caret-down "></i>
							</a>

							<ul class="dropdown-menu">
                <li>
                  <a href="#">个人信息</a>
                </li>
                <li>
                  <a href="#">密码变更</a>
                </li>
								<li>
									<a href="#">退出登陆</a>
								</li>
							</ul>
						</li>
					</ul>
					<!-- end: TOP NAVIGATION MENU -->
				</div>
			</div>
			<!-- end: TOPBAR CONTAINER -->
		</header>
		<!-- end: TOPBAR -->
		<!-- start: PAGESLIDE LEFT -->
		<a class="closedbar inner hidden-sm hidden-xs" href="#"></a>
		<nav id="pageslide-left" class="pageslide inner">
			<div class="navbar-content">
				<!-- start: SIDEBAR -->
				<div class="main-navigation left-wrapper transition-left">
					<div class="navigation-toggler hidden-sm hidden-xs">
						<a href="#main-navbar" class="sb-toggle-left"></a>
					</div>
					<div class="user-profile border-top padding-horizontal-10 block">
						<div class="inline-block">
                          <span class="fileupload-preview fileupload-exists thumbnail" style="line-height: 42px;text-align: center;width:50px;height: 50px;display: block;">
                              <%= image_tag 'anonymous.jpg' ,:class => 'img_style',:style=>'display: inline-block;vertical-align: middle;max-height: 100%;'%>
                            </span>
                        </div>
						<div class="inline-block">
							<h5 class="no-margin"></h5>
							<h4 class="no-margin">管理者</h4>

						</div>
					</div>
					<!-- start: MAIN NAVIGATION MENU -->
                  <%= render :partial => '/common/menu' %>

					<!-- end: MAIN NAVIGATION MENU -->
				</div>
				<!-- end: SIDEBAR -->
			</div>
			<div class="slide-tools">
				<div class="col-xs-6 text-left no-padding">
				</div>
				<div class="col-xs-6 text-right no-padding">
					<a class="btn btn-sm log-out text-right" href="#">
						<i class="fa fa-power-off"></i> 退出登陆
					</a>
				</div>
			</div>
		</nav>
		<!-- end: PAGESLIDE LEFT -->

app/views/common/_menu.html.erb
<ul class="main-navigation-menu">
  <li class="main-navigation-menu-default">
    <a href="#" data-turbolinks="false">
      <i class="fa fa-home"></i> <span class="title"> 主页 </span><span class="label label-default pull-right "></span>
    </a>
  </li>

  <li class='main-navigation-menu-account' style="display:block">
    <a href="javascript:void(0)">
      <i class="fa fa-users"></i> <span class="title">用户管理 </span><i class="icon-arrow"></i>
    </a>
    <ul class="sub-menu">
      <li>
        <a href="#"  data-turbolinks="false">
          <i class="fa fa-list"></i><span class="title">用户列表</span>
        </a>
      </li>
      <li>
        <a href="#"  data-turbolinks="false">
          <i class="fa fa-pencil"></i>  <span class="title">用户分析</span>
        </a>
      </li>
    </ul>
  </li>

  <li class='main-navigation-menu-lp-manage'>
    <a href="javascript:void(0)">
      <i class="fa fa-music"></i> <span class="title">曲目管理 </span><i class="icon-arrow"></i>
    </a>
    <ul class="sub-menu">
      <li>
        <a href="#"  data-turbolinks="false">
          <i class="fa fa-list"></i>  <span class="title">曲目列表</span>
        </a>
      </li>
    </ul>
  </li>

<!--  <li class='main-navigation-menu-data'>-->
<!--    <a href="javascript:void(0);" class="active">-->
<!--      <i class="fa fa-cubes"></i> <span class="title">入稿URL管理 </span> <i class="icon-arrow"></i>-->
<!--    </a>-->
<!--    <ul class="sub-menu">-->
<!--      <li>-->
<!--        <a href="/draft/list" data-turbolinks="false">-->
<!--          <i class="fa fa-money"></i><span class="title"> 入稿URL一覧 </span>-->
<!--        </a>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </li>-->

<!--  <li class='main-navigation-menu-access'>-->
<!--    <a href="javascript:;" class="active">-->
<!--      <i class="fa fa-graduation-cap"></i> <span class="title">アクセス集計・請求確認 </span> <i class="icon-arrow"></i>-->
<!--    </a>-->
<!--    <ul class="sub-menu">-->
<!--      <li>-->
<!--        <a href="/draft/access_analysis" data-turbolinks="false">-->
<!--          <i class="fa fa-line-chart"></i><span class="title"> 入稿URLごとのアクセス集計 </span>-->
<!--        </a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="/draft/use_situation" data-turbolinks="false">-->
<!--          <i class="fa fa-bookmark"></i><span class="title"> ご利用状況確認 </span>-->
<!--        </a>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </li>-->

  <li class='main-navigation-menu-application'>
    <a href="javascript:void(0)">
      <i class="fa fa-gear"></i> <span class="title">设定</span><i class="icon-arrow"></i> <span class="arrow "></span>
    </a>
    <ul class="sub-menu">
      <li>
        <a href="#" data-turbolinks="false">
          <i class="fa fa-wrench"></i><span class="title">系统设定</span>
        </a>
      </li>
      <li>
        <a href="#" data-turbolinks="false">
          <i class="fa fa-wrench"></i><span class="title">页面设置</span>
        </a>
      </li>
    </ul>
  </li>
  <li class="main-navigation-menu-file">
    <a href="#" data-turbolinks="false">
      <i class="fa fa-paperclip "></i><span class="title"> 文件管理 </span>
    </a>
  </li>
</ul>

app/views/common/_scripts.html.erb
<%= javascript_include_tag 'js/app', 'data-turbolinks-track' => false, 'data-turbolinks-eval' => false %>

<script>
    jQuery(document).ready(function() {

        if(toastr){
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "0",
                "extendedTimeOut": "0",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
            <% flash.each do |key, value| %>
            <% if value.present? %>
            toastr.<%= switch_key(key) %>('<%= value.html_safe %>');
            <% end %>
            <% end %>
            <%- flash.clear() -%>
        };

        Main.init();

        // 初始化日期控件
        // initDateRange();

        // 清空输入框
        // resetSearchInput();


    });

</script>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- InstanceBeginEditable name="title" -->
    <title>LeyiCms</title>
    <!-- InstanceEndEditable -->
    <!-- start: META -->
    <meta charset="utf-8"/>
    <!--[if IE]>
    <meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1"/><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- end: META -->
    <!-- start: MAIN CSS -->
<!--    <link rel="shortcut icon" type="image/ico" href="/favicon.ico"/>-->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style type="text/css">
    .main-navigation-menu-default > a{
      background: #e5e8ed !important;
      border-top: none !important;
      color: #2C2F3B;
    }
    ul{
      list-style:none;
    }
    ul.main-navigation-menu li ul.sub-menu-level2 {
      display: block;
    }
    ul.main-navigation-menu  .main-navigation-menu-default ul.sub-menu{
      display:block;
    }

    .main-navigation-menu .main-navigation-menu-default ul.sub-menu li:nth-child(1) a{
      background: #f1f3f6;
    }
    .nav-tabs > li.active a{
      min-height: 40px;
    }
  </style>
  <body>
    <%= render :partial => '/common/before' %>
    <div class="main-wrapper">
      <!-- start: MAIN CONTAINER -->
      <%= yield %>

      <!-- end: MAIN CONTAINER -->
    </div>
    <%= render :partial => '/common/scripts' %>
  </body>
</html>

<script type="text/javascript">
    $(document).ready(function(){
        // 菜单展开
        $("ul.main-navigation-menu  li.main-navigation-menu-default").addClass('open');
    });


</script>

app/views/user/list.html.erb
<div class="main-container inner">
  <!-- start: PAGE -->
  <div class="main-content">
    <!-- start: PANEL CONFIGURATION MODAL FORM -->
    <div class="modal fade" id="panel-config" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Panel Configuration</h4>
          </div>
          <div class="modal-body">Here will be a configuration form</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!-- end: SPANEL CONFIGURATION MODAL FORM -->
    <div class="container">
      <!-- start: PAGE HEADER -->
      <!-- InstanceBeginEditable name="content" -->
      <!-- start: PAGE HEADER -->
      <!-- start: TOOLBAR -->
      <div class="toolbar row">
        <div class="col-sm-6 hidden-xs">
          <div class="page-header">
            <h3>
              <i class="menu_icon"></i>&nbsp;用户管理
<!--              <small>会社管理マスター</small>-->
            </h3>
          </div>
        </div>
        <div class="col-sm-6 col-xs-12">
          <div class="toolbar-tools pull-right">
            <!-- start: TOP NAVIGATION MENU -->
            <ul class="nav navbar-right">
              <!-- start: TO-DO DROPDOWN -->
              <li class="dropdown">
<!--                <button class="btn btn-orange add-row" onClick="javascript:location.href='new.html'">-->
<!--                  新規登録 <i class="fa fa-plus"></i>-->
<!--                </button>-->
              </li>
              <!--<li class="dropdown">
                <button class="btn btn-blue add-row" onClick="javascript:location.href='password.html'">
                  パスワード変更
                </button>
              </li>-->
            </ul>
            <!-- end: TOP NAVIGATION MENU -->
          </div>
        </div>
      </div>
      <!-- end: TOOLBAR -->
      <!-- end: PAGE HEADER -->
      <!-- start: BREADCRUMB -->
      <div class="row buttonSp">
        <div class="col-md-12">
          <ol class="breadcrumb">
            <li>
              <a href="/user/admin/company/list.html">
                用户管理
              </a>
            </li>
            <li class="active">
              用户列表
            </li>
          </ol>
        </div>
        <div class="col-md-12">
        <span class="buttonSpSpan">
<!--            <button class="btn btn-orange add-row" onClick="javascript:location.href='new.html'">-->
<!--                新規登録 <i class="fa fa-plus"></i>-->
<!--            </button>-->
        </span>
        </div>
      </div><!-- end: BREADCRUMB -->

      <div class="row">
        <div class="col-md-12">
          <!-- start: FORM VALIDATION 1 PANEL -->
          <div class="panel panel-white">
            <div class="panel-heading">
              <h4> <i class="fa fa-search"></i>查询</h4>
              <div class="panel-tools">
                <div class="dropdown">
                  <a class="panel-collapse collapses" href="#"> <i class="fa fa-angle-up"></i>
                    <span>可折叠</span>
                  </a>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <p>请输入搜索条件。</p>
              <hr>
              <form method="GET"  accept-charset="UTF-8" role="form" novalidate>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="control-label">用户名</label>
                      <input class="form-control" type="text" value="">
                    </div>
<!--                    <div class="form-group">-->
<!--                      <label class="control-label">会社名（フリガナ）</label>-->
<!--                      <input class="form-control" type="text" value="">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                      <label class="control-label">郵便番号</label>-->
<!--                      <input class="form-control" type="text" value="">-->
<!--                    </div>-->
                  </div>

                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="control-label">手机号</label>
                      <input class="form-control" type="text" value="">
                    </div>
<!--                    <div class="form-group">-->
<!--                      <label class="control-label">住所</label>-->
<!--                      <input class="form-control" type="text" value="">-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                      <label class="control-label">電話番号</label>-->
<!--                      <input class="form-control" type="text" value="">-->
<!--                    </div>-->
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-3"></div>
                  <div class="col-md-3">
                    <button class="btn btn-info btn-block" type="submit">
                      查询
                      <i class="fa fa-search"></i>
                    </button>
                  </div>
                  <div class="col-md-2">
                    <button class="btn btn-yellow btn-block W150" type="reset">
                      清空条件
                      <i class="fa fa-rotate-left"></i>
                    </button>
                  </div>
                  <div class="col-md-4"></div>
                </div>
              </form>
            </div>
          </div>
          <!-- end: FORM VALIDATION 1 PANEL --> </div>
      </div><div class="row">
      <div class="col-md-12">
        <!-- start: DYNAMIC TABLE PANEL -->
        <div class="panel panel-white">
          <div class="panel-heading">
            <h4 class="panel-title">
              <i class="fa fa-list"></i>
              検索結果
              <span class="text-bold">会社一覧</span>
            </h4>
            <div class="panel-tools">
              <div class="dropdown">
                <a data-toggle="dropdown" class="btn btn-xs dropdown-toggle btn-transparent-grey">
                  <i class="fa fa-cog"></i>
                </a>
                <ul class="dropdown-menu dropdown-light pull-right" role="menu">
                  <li>
                    <a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>可折叠</span> </a>
                  </li>
                  <li>
                    <a class="panel-refresh" href="#">
                      <i class="fa fa-refresh"></i> <span>刷新数据</span>
                    </a>
                  </li>
                  <li>
                    <a class="panel-expand" href="#">
                      <i class="fa fa-expand"></i> <span>全屏展示</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
              <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
                <thead>
                <tr role="row">
                  <th>No</th>
                  <th>用户名</th>
                  <th>手机号</th>
                  <th>邮箱</th>
                  <th>地址</th>
                  <th>等级</th>
                  <th>积分</th>
                  <th>加入时间</th>
                  <th>登录总时间</th>
                  <th>练习时间</th>
                  <th>分享次数</th>
                  <!--<th>登録アンケート<br>回答URL</th>-->
                  <th width="10%">操作</th>
                </tr>
                </thead>
                <tr role="row">
                  <td>1</td>
                  <td>kk</td>
                  <td>12345633</td>
                  <td>12345633@123</td>
                  <td>北京</td>
                  <td>22</td>
                  <td>44</td>
                  <td></td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <!--<td><a href="http://html.fortune.a-it.jp?p=1257813546" target="_blank">http://html.fortune.a-it.jp?p=1257813546</a></td>-->
                  <td class="center">
                    <div class="visible-md visible-lg visible-sm visible-xs">
                      <a href="add.html" >
                        详细
                      </a> |
                      <a href="edit.html">
                        编辑
                      </a> |
                      <a href="#" data-method="delete" data-confirm="会社を削除します。">
                        删除
                      </a>
                    </div>

                  </td>
                </tr>
                <tr role="row">
                  <td>2</td>
                  <td>kk</td>
                  <td>12345633</td>
                  <td>12345633@123</td>
                  <td>北京</td>
                  <td>22</td>
                  <td>44</td>
                  <td></td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <!--<td><a href="http://html.fortune.a-it.jp?p=1257813546" target="_blank">http://html.fortune.a-it.jp?p=1257813546</a></td>-->
                  <td class="center">
                    <div class="visible-md visible-lg visible-sm visible-xs">
                      <a href="add.html" >
                        详细
                      </a> |
                      <a href="edit.html">
                        编辑
                      </a> |
                      <a href="#" data-method="delete" data-confirm="会社を削除します。">
                        删除
                      </a>
                    </div>

                  </td>
                </tr>
                <tr role="row">
                  <td>3</td>
                  <td>kk</td>
                  <td>12345633</td>
                  <td>12345633@123</td>
                  <td>北京</td>
                  <td>22</td>
                  <td>44</td>
                  <td></td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <td align="center">100</td>
                  <!--<td><a href="http://html.fortune.a-it.jp?p=1257813546" target="_blank">http://html.fortune.a-it.jp?p=1257813546</a></td>-->
                  <td class="center">
                    <div class="visible-md visible-lg visible-sm visible-xs">
                      <a href="add.html" >
                        详细
                      </a> |
                      <a href="edit.html">
                        编辑
                      </a> |
                      <a href="#" data-method="delete" data-confirm="会社を削除します。">
                        删除
                      </a>
                    </div>
                  </td>
                </tr>
              </table>
              <div class="dataTables_info" role="status" aria-live="polite">
                共9件1-3在显示
              </div>
              <div class="dataTables_paginate paging_simple_numbers"><ul class="pagination"><li class="disabled"><span>«</span></li> <li class="active"><span>1</span></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li><a href="#">4</a></li><li><a href="#">5</a></li> <li><a href="#" rel="next">»</a></li></ul></div>
            </div>
          </div>
        </div>
        <!-- end: DYNAMIC TABLE PANEL -->
      </div>
    </div>
      <!-- InstanceEndEditable -->
      <!-- end: PAGE HEADER -->
    </div>
    <div class="subviews">
      <div class="subviews-container"></div>
    </div>
  </div>
  <!-- end: PAGE -->
</div>

app/views/user/login.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Page title -->
  <title></title>
  <%= javascript_include_tag 'login_application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'login_application', 'media' => 'all', 'data-turbolinks-track' => true %>
</head>
<body class="login">

<!-- Simple splash screen-->
<!--<div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>カタリベCMS</h1><p>ページ読み込み中... </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>-->
<!--[if lt IE 7]>
<p class="alert alert-danger">You are using an <strong>outdated</strong> browser.
<![endif]-->

<div class="color-line"></div>

<div class="login_top_links">
  <!--<a href="#"><i class="fa fa-question-circle"></i> HELP</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="#"><i class="fa fa-commenting"></i> お問い合わせ</a>-->
</div>
<div class="login-container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center m-b-md">
        <h3></h3>
        <!-- <small>管理画面</small>-->
      </div>
      <div class="hpanel">
        <div class="panel-body">
          <hr>
          <%= form_tag(login_user_index_path) do %>
            <div class="form-group">
              <label class="control-label" for="username">用户名</label>
              <span class="input-icon">
                                    <input type="text" style="ime-mode:disabled;" class="form-control" name="phone" placeholder="请输入用户名->admin" value="<%= params[:phone] %>">
                                <i class="fa fa-user"></i> </span>

            </div>
            <div class="fform-group form-actions">
              <label class="control-label" for="username">密码</label>
              <span class="input-icon">
									<input type="password" class="form-control password" name="password" placeholder="请输入密码->admin" value="<%= params[:password] %>">
									<i class="fa fa-lock"></i>
                                </span>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-green pull-right">
                登陆 <i class="fa fa-arrow-circle-right"></i>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      2017 &copy; Copyright(C) leyi Inc. All Rights Reserved.
    </div>
  </div>
</div>

</body>
</html>
<script type="text/javascript">
    $(function () {
        if (toastr) {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "0",
                "extendedTimeOut": "0",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
            <% flash.each do |key, value| %>
            <% if value.present? %>
            toastr.<%= switch_key(key) %>('<%= value.html_safe %>');
            <% end %>
            <% end %>
            <%- flash.clear() -%>
        }
    });
</script>